version: "3"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=devsoloyoi"
      - "POSTGRES_DB=nestjs-query"
    expose:
      - "5432"
    ports:
      - "5432:5432"